"""add product_image to order_items

Revision ID: 0b72d32efc6a
Revises: a7129cfd5ac1
Create Date: 2026-03-22 20:58:00.901842

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0b72d32efc6a"
down_revision: Union[str, Sequence[str], None] = "a7129cfd5ac1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "order_items", sa.Column("product_image", sa.String(length=512), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("order_items", "product_image")
    # ### end Alembic commands ###
